### PR TITLE
Emit es6 imports for TypeScript files

### LINKED ISSUE #519: Commonjs requires are always emitted for TypeScript
For the following Rescript file:
```
let rootRefContext: React.Context.t(React.ref(Js.Nullable.t(Dom.element))) =
  React.createContext(React.{current: Js.Nullable.null});

module GlobalPortal = {
  [@react.component]
  let make = (~children: React.element) => {
    let rootRef = React.useContext(rootRefContext);
    switch (rootRef.current->Js.Nullable.toOption) {
    | None => React.null
    | Some(rootRef) => ReactDOM.createPortal(children, rootRef)
    };
  };
};

[@genType.as "GlobalPortal"]
let globalPortal = GlobalPortal.make;
```

The generated typescript is as follows
```
/* TypeScript file generated from LayerContext.re by genType. */
/* eslint-disable import/first */


import * as React from 'react';

// tslint:disable-next-line:no-var-requires
const LayerContextBS = require('./LayerContext.bs');

// tslint:disable-next-line:interface-over-type-literal
export type GlobalPortal_Props = { readonly children: React.ReactNode };

export const GlobalPortal: React.ComponentType<{ readonly children: React.ReactNode }> = LayerContextBS.globalPortal;
```

It seems like the usage of require is unnecessary in this case.

### PR DESCRIPTION
**Pull request by wokalski**
Fixes #519 

Tests need to be adjusted before merging.

### CODE REVIEW

**Comment by cristianoc** [comment]
@wokalski thanks for putting this up.

The issues that come up with es6 imports have to do with the fact that TS treats them as types, while `require`'s are untyped.

For example:

```
Could not find a declaration file for module 'bs-platform/lib/es6/curry.js'. '/Users/cristianoc/reasonml/genType/examples/typescript-react-example/node_modules/bs-platform/lib/es6/curry.js' implicitly has an 'any' type.
  Try `npm install @types/bs-platform` if it exists or add a new declaration (.d.ts) file containing `declare module 'bs-platform/lib/es6/curry.js';`  TS7016
```

Wondering what code (or silencing comment) should be generated to make it treat imports as untyped.

**Comment by wokalski** [comment]
@cristianoc I added two more commits on my branch but for some reason they don't pop up here. You can see them here:
https://github.com/dialohq/genType/commits/es6-typescript-imports

**Comment by wokalski** [comment]
@cristianoc I have addressed the issue with a workaround.
1. We first import using es6 syntax and ignore the type error
2. We cast the imported value to any

```
// @ts.ignore: Ignore any on import
import * as ModuleBsEs6Import from "./module.bs";
const ModuleBs: any = ModuleBsEs6Import;
```

The only possible drawback is when there are any cases when we depend on type definitions from imported modules which IIUC should not happen.

**Comment by cristianoc** [comment]
@wokalski thanks a lot, this looks great.
Would you change the suffix from `Es6Import` to `__Es6Import` to make name clashes a bit less likely?

**Comment by wokalski** [comment]
@cristianoc On another note - would you accept a contribution either with esy.json or with instructions how to develop using esy? It doesn't require any changes if you set `esy.buildsInSource: "build"` in esy.json.

Another thing I'd like to do is adding `test` script to all examples and them in integration test suite. For typescript the test script would call `tsc` and for flow it'd run `flow`. At first I didn't notice the issue you mentioned in the first comment because I foolishly just ran tests.

**Comment by cristianoc** [comment]
Amazing, thank you so much.

**Comment by wokalski** [comment]
@cristianoc are you going to release the change soon or should I depend on master with opam/esy in my project?

**Comment by cristianoc** [comment]
@wokalski planning to do a release today or tomorrow.

**Comment by cristianoc** [comment]
@wokalski in release `3.45.0`.

**Pull request merged**
